
stages:
  - test

test-windows-amd64:
  stage: test
  tags:
    - msbuild
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 2014 Win64" ..
    - msbuild ALL_BUILD.vcxproj

test-windows-386:
  stage: test
  tags:
    - msbuild
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 2014" ..
    - msbuild ALL_BUILD.vcxproj

test-linux-amd64:
  stage: test
  tags:
    - docker-capsule-64
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

test-linux-386:
  stage: test
  tags:
    - docker-capsule-32
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

test-macos-amd64:
  stage: test
  tags:
    - darwin
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
